/* Isolated UI regression. No real accounts, clipboard, model calls or workspace data. */
const {chromium}=require('playwright'),assert=require('assert/strict'),fs=require('fs'),path=require('path');
const {pathToFileURL}=require('url');
(async()=>{
 const [html,out,before]=process.argv.slice(2);fs.mkdirSync(out,{recursive:true});
 const browser=await chromium.launch({channel:'msedge',headless:true});
 try{
  const page=await browser.newPage({viewport:{width:1440,height:960},acceptDownloads:true,reducedMotion:'reduce'}),errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  await page.addInitScript(()=>{
   const profile={id:'m1',name:'测试模型',preset:'deepseek',model:'deepseek-v4-pro',base_url:'https://api.deepseek.com',has_key:true};
   const projects=[{id:'p1',name:'研究笔记'}],frames=[{id:'f1',name:'阅读与思考',project_id:'p1'}];
   const theme={name:'海边书房',colors:{paper:'#EAF0F3',surface:'#F6FAFC',ink:'#20323D',accent:'#31677D',rail:'#20323D',rail_ink:'#EAF0F3'}};
   const load=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))||f}catch(_){return f}};
   window.fixture={calls:[],account:load('test-account',null),preferences:load('test-appearance',{mode:'system',theme:null}),theme,failSave:false,messages:[{seq:2,message_id:'m2',role:'assistant',content:'我们可以从一个清晰的问题开始。'}]};
   const api={
    get_state:async()=>({profiles:[profile],active_profile_id:'m1',appearance:{theme:'ink-autumn',locale:'zh'},themes:[],presets:[{id:'deepseek',label:'DeepSeek',model:profile.model,base_url:profile.base_url,editable_base_url:true}]}),
    list_entity_states:async()=>({entities:[],next_offset:null}),
    list_session_models:async()=>({models:[{...profile,available:true}],binding:{profile_id:'mp1',revision:1,native_profile_id:'m1',credential_ready:true,reasoning:{revision:'cap1',choices:[{id:'default',available:true},{id:'low',available:true,native_value:'low'}]}}}),
    account_request:async p=>{fixture.calls.push(['account',p.operation]);if(p.operation==='logout')fixture.account=null;else if(p.operation==='update_profile'){if(!fixture.account)return {ok:false,message:'ACCOUNT_LOGIN_REQUIRED'};fixture.account={...fixture.account,display_name:p.display_name,bio:p.bio,avatar:p.avatar};}else if(p.operation!=='state')fixture.account={email:p.email,display_name:'读者',bio:'',avatar:'',local:true};localStorage.setItem('test-account',JSON.stringify(fixture.account));return {ok:true,account:fixture.account,...(p.operation==='register'?{recovery_code:'isolated-fixture-recovery-code'}:{})}},
    workspace_preferences:async p=>{fixture.calls.push(['appearance',structuredClone(p)]);if(p.operation==='validate')return {ok:true,theme:p.theme};if(p.operation==='save'){if(fixture.failSave)return {ok:false,message:'THEME_UNAVAILABLE'};fixture.preferences={mode:p.mode,theme:p.theme};localStorage.setItem('test-appearance',JSON.stringify(fixture.preferences));}return {ok:true,preferences:structuredClone(fixture.preferences)}},
    save_appearance:async p=>({ok:true,appearance:p}),save_profile:async()=>({ok:true}),paste_text:async()=>({ok:true,text:'粘贴文本'}),copy_text:async p=>{fixture.calls.push(['copy',p.text]);return {ok:true}},return_to_start:async()=>{fixture.calls.push(['home']);return {ok:true}},
    workbench_request:async p=>{fixture.calls.push([p.operation,p]);let data={};if(p.operation==='projects')data={projects};if(p.operation==='frames')data={frames};if(p.operation==='create_frame'){const f={id:'f'+(frames.length+1),name:'新对话',project_id:'p1'};frames.push(f);data=f;}if(p.operation==='messages')data=p.before?{messages:[{seq:1,message_id:'m1',role:'user',content:'较早的消息'}],has_earlier:false}:{messages:fixture.messages,has_earlier:true,next_before_seq:2};if(p.operation==='execution')data={owner:null};if(p.operation==='feedback')data={feedback:{}};return {ok:true,data}}
   };window.pywebview={api};addEventListener('DOMContentLoaded',()=>dispatchEvent(new Event('pywebviewready')));
  });
  if(before){await page.goto(pathToFileURL(before).href);await page.locator('#history .history-item').first().waitFor();await page.screenshot({path:path.join(out,'before-workspace.png')});}
  await page.goto(pathToFileURL(html).href);await page.locator('#history .history-item').first().waitFor();
  await page.screenshot({path:path.join(out,'after-workspace.png')});
  assert.equal(await page.locator('#identity-name').textContent(),'访客');
  await page.locator('#settings-button').click();await page.locator('[data-settings-tab=appearance]').click();await page.locator('#appearance-theme option').first().waitFor({state:'attached'});
  await page.screenshot({path:path.join(out,'appearance.png')});await page.locator('#close-settings').click();
  await page.locator('#profile-button').click();await page.locator('[data-auth-mode=register]').click();await page.locator('#profile-email').fill('reader@example.com');await page.locator('#profile-password').fill('test-password-long');await page.locator('#profile-confirm').fill('test-password-long');await page.locator('#profile-auth-submit').click();await page.locator('#profile-form').waitFor({state:'visible'});
  await page.locator('#profile-name').fill('林间读者');await page.locator('#profile-bio').fill('阅读、写作，记录每天的新问题。');
  const png=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=c.height=64;const x=c.getContext('2d');x.fillStyle='#37687c';x.fillRect(0,0,64,64);x.fillStyle='#f4e4c5';x.beginPath();x.arc(32,32,17,0,7);x.fill();return c.toDataURL().split(',')[1]});
  await page.locator('#profile-avatar-file').setInputFiles({name:'avatar.png',mimeType:'image/png',buffer:Buffer.from(png,'base64')});await page.waitForFunction(()=>document.querySelector('#profile-avatar img'));
  await page.locator('#profile-save').click();await page.waitForFunction(()=>document.querySelector('#identity-name').textContent==='林间读者');await page.screenshot({path:path.join(out,'profile.png')});await page.locator('#profile-close').click();
  await page.waitForFunction(()=>document.querySelector('#profile-issued-code').textContent==='');await page.reload();await page.waitForFunction(()=>document.querySelector('#identity-name').textContent==='林间读者');assert.equal(await page.locator('#identity-avatar img').count(),1);
  await page.locator('#settings-button').click();await page.locator('[data-settings-tab=appearance]').click();await page.locator('#appearance-mode').selectOption('dark');await page.locator('#appearance-save').click();await page.waitForFunction(()=>document.documentElement.dataset.leoMode==='dark');await page.screenshot({path:path.join(out,'dark-settings.png')});
  const upload=async()=>page.locator('#custom-theme-file').setInputFiles({name:'theme.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(await page.evaluate(()=>fixture.theme)))});
  await upload();await page.locator('#theme-preview-dialog').waitFor({state:'visible'});await page.screenshot({path:path.join(out,'theme-preview.png')});await page.locator('#theme-preview-cancel').click();assert.equal(await page.evaluate(()=>fixture.preferences.theme),null);
  await upload();await page.evaluate(()=>fixture.failSave=true);await page.locator('#theme-preview-apply').click();await page.waitForFunction(()=>document.querySelector('#theme-preview-status').textContent.length>0);assert.equal(await page.locator('#theme-preview-dialog').isVisible(),true);assert.equal(await page.evaluate(()=>fixture.preferences.theme),null);
  await page.evaluate(()=>fixture.failSave=false);await page.locator('#theme-preview-apply').click();await page.locator('#theme-preview-dialog').waitFor({state:'hidden'});await page.reload();await page.waitForFunction(()=>document.documentElement.style.getPropertyValue('--paper')==='#EAF0F3');
  await page.locator('#history .history-item').first().click();await page.waitForFunction(()=>document.querySelector('#messages').textContent.includes('清晰'));
  await page.locator('#message-input').fill('原始草稿');await page.locator('#message-input').evaluate(e=>{e.focus();e.setSelectionRange(0,4)});
  await page.getByRole('menuitem',{name:'编辑',exact:true}).click();await page.getByRole('menuitem',{name:/粘贴/}).click();assert.equal(await page.locator('#message-input').inputValue(),'粘贴文本');
  await page.locator('#message-input').focus();await page.getByRole('menuitem',{name:'编辑',exact:true}).click();await page.getByRole('menuitem',{name:/撤销/}).click();assert.equal(await page.locator('#message-input').inputValue(),'原始草稿');
  await page.getByRole('menuitem',{name:'文件',exact:true}).click();await page.screenshot({path:path.join(out,'file-menu.png')});const event=page.waitForEvent('download');await page.getByRole('menuitem',{name:'导出当前对话…'}).click();const dl=await event;const data=fs.readFileSync(await dl.path(),'utf8');assert.ok(data.includes('较早的消息')&&data.includes('清晰的问题'));
  await page.getByRole('menuitem',{name:'视图',exact:true}).click();await page.getByRole('menuitem',{name:'显示 / 隐藏侧栏'}).click();assert.equal(await page.locator('.rail').isVisible(),false);await page.locator('#sidebar-toggle').click();
  await page.getByRole('menuitem',{name:'帮助',exact:true}).click();await page.getByRole('menuitem',{name:'关于 Leo AI Studio'}).click();assert.equal(await page.locator('[data-settings-pane=about]').isVisible(),true);await page.locator('[data-settings-tab=appearance]').click();await page.locator('#theme-prompt').fill('安静的蓝色');await page.locator('#theme-conversation').click();await page.waitForFunction(()=>document.querySelector('#message-input').value.includes('安静的蓝色'));assert.equal(await page.evaluate(()=>fixture.calls.filter(c=>c[0]==='send').length),0);
  await page.evaluate(()=>fixture.messages=[{seq:3,message_id:'theme',role:'assistant',content:'```json\n'+JSON.stringify(fixture.theme)+'\n```'}]);await page.locator('#history .history-item').first().click();await page.getByRole('button',{name:'预览主题',exact:true}).click();await page.locator('#theme-preview-dialog').waitFor({state:'visible'});await page.locator('#theme-preview-cancel').click();
  await page.locator('#profile-button').click();await page.locator('#profile-logout').click();assert.equal(await page.locator('#identity-name').textContent(),'访客');await page.locator('#profile-close').click();await page.locator('#settings-button').click();assert.equal(await page.locator('#settings-dialog').isVisible(),true);await page.locator('#close-settings').click();
  await page.setViewportSize({width:840,height:600});await page.screenshot({path:path.join(out,'compact.png')});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);const box=await page.locator('#profile-button').boundingBox();assert.ok(box.y+box.height<=600);
  assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'profile-checks.json'),JSON.stringify({passed:true,checks:['guest settings','registration to editable profile','avatar upload and restart','preview cancel','save failure preserves theme','custom theme persistence','paste and undo','complete paginated export','sidebar visibility','about','theme conversation draft without auto send','reply theme preview','logout','compact layout'],page_errors:errors},null,2));
 }finally{await browser.close()}
})().catch(e=>{console.error(e);process.exitCode=1});
